[package]
name = "reth-stages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Staged syncing primitives used in reth."

[lints]
workspace = true

[dependencies]
# reth
reth-exex.workspace = true
reth-primitives.workspace = true
reth-interfaces.workspace = true
reth-db.workspace = true
reth-codecs.workspace = true
reth-provider.workspace = true
reth-trie = { workspace = true, features = ["metrics"] }
reth-etl.workspace = true
reth-config.workspace = true
reth-stages-api = { workspace = true, features = ["test-utils"] }
reth-consensus.workspace = true
reth-evm.workspace = true
reth-revm.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }
futures-util.workspace = true

# observability
tracing.workspace = true

# misc
thiserror.workspace = true
itertools.workspace = true
rayon.workspace = true
cfg-if = "1.0.0"
num-traits = "0.2.15"
tempfile = { workspace = true, optional = true }

[dev-dependencies]
# reth
reth-primitives = { workspace = true, features = ["test-utils", "arbitrary"] }
reth-db = { workspace = true, features = ["test-utils", "mdbx"] }
reth-evm-bsc.workspace = true
reth-evm-ethereum.workspace = true
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-consensus = { workspace = true, features = ["test-utils"] }
reth-downloaders.workspace = true
reth-revm.workspace = true
reth-static-file.workspace = true
reth-trie = { workspace = true, features = ["test-utils"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-network-types.workspace = true

alloy-rlp.workspace = true
itertools.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "macros"] }
assert_matches.workspace = true
rand.workspace = true
paste.workspace = true
tempfile.workspace = true

# Stage benchmarks
criterion = { workspace = true, features = ["async_tokio"] }

# io
serde_json.workspace = true

[target.'cfg(not(target_os = "windows"))'.dev-dependencies]
pprof = { workspace = true, features = [
    "flamegraph",
    "frame-pointer",
    "criterion",
] }

[features]
bsc = [
    "reth-evm-bsc/bsc",
]
test-utils = [
    "reth-interfaces/test-utils",
    "reth-db/test-utils",
    "reth-provider/test-utils",
    "reth-stages-api/test-utils",
    "dep:tempfile",
]

[[bench]]
name = "criterion"
harness = false
required-features = ["test-utils"]
